In [13]:
import pandas as pd
import numpy as np
from haversine import haversine

distance = pd.read_csv("C:\\Users\\USER\\Desktop\\샘플데이터\\정제 데이터\\전처리데이터.csv", engine='python')

In [14]:
distance.fillna(0, inplace=True)

In [15]:
distance

,gid,주차장,건물1,건물2,건물3,관공서,생산가능인구,전기차,충전소,교통량,유동인구,경도,위도
0,다바928626,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.419890,36.761921
1,다바928625,0.0,0,0,0,0,0.0,0,0,0.0,137.26,127.419891,36.761020
2,다바928624,0.0,5,0,0,0,0.0,0,0,0.0,66.22,127.419892,36.760118
3,다바928623,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.419893,36.759217
4,다바928622,0.0,0,0,0,0,0.0,0,0,0.0,40.98,127.419894,36.758315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64796,다바561511,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009366,36.657266
64797,다바561510,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009372,36.656365
64798,다바561509,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009377,36.655464
64799,다바560512,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.008241,36.658163
64800,다바560511,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.008247,36.657262

In [25]:
distance['거리_전기차'] = 0
distance['거리_충전소'] = 0
distance['거리_교통량'] = 0

In [26]:
distance

,gid,주차장,건물1,건물2,건물3,관공서,생산가능인구,전기차,충전소,교통량,유동인구,경도,위도,거리_전기차,거리_충전소,거리_교통량
0,다바928626,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.419890,36.761921,0,0,0
1,다바928625,0.0,0,0,0,0,0.0,0,0,0.0,137.26,127.419891,36.761020,0,0,0
2,다바928624,0.0,5,0,0,0,0.0,0,0,0.0,66.22,127.419892,36.760118,0,0,0
3,다바928623,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.419893,36.759217,0,0,0
4,다바928622,0.0,0,0,0,0,0.0,0,0,0.0,40.98,127.419894,36.758315,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64796,다바561511,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009366,36.657266,0,0,0
64797,다바561510,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009372,36.656365,0,0,0
64798,다바561509,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.009377,36.655464,0,0,0
64799,다바560512,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.008241,36.658163,0,0,0
64800,다바560511,0.0,0,0,0,0,0.0,0,0,0.0,0.00,127.008247,36.657262,0,0,0

In [27]:
distance2=distance[distance['전기차']!=0]

In [28]:
for j in range(0, len(distance)):
    for i in range(0, len(distance2)):
        lon = distance['경도'][j]
        lat = distance['위도'][j]
        lon2 = distance2['경도'].reset_index(drop=True)[i]
        lat2 = distance2['위도'].reset_index(drop=True)[i]
        a = (lat, lon)
        b = (lat2, lon2)
        c = haversine(a, b) * 1000
        if c <= 500:
             distance['거리_전기차'][j] = 1

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [30]:
distance3=distance[distance['충전소']!=0]

In [31]:
for j in range(0, len(distance)):
    for i in range(0, len(distance3)):
        lon = distance['경도'][j]
        lat = distance['위도'][j]
        lon2 = distance3['경도'].reset_index(drop=True)[i]
        lat2 = distance3['위도'].reset_index(drop=True)[i]
        a = (lat, lon)
        b = (lat2, lon2)
        c = haversine(a, b) * 1000
        if c <= 500:
             distance['거리_충전소'][j] = 1

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [40]:
distance4=distance[distance['교통량']!=0]

In [41]:
for j in range(0, len(distance)):
    for i in range(0, len(distance4)):
        lon = distance['경도'][j]
        lat = distance['위도'][j]
        lon2 = distance4['경도'].reset_index(drop=True)[i]
        lat2 = distance4['위도'].reset_index(drop=True)[i]
        a = (lat, lon)
        b = (lat2, lon2)
        c = haversine(a, b) * 1000
        if c <= 500:
             distance['거리_교통량'][j] = 1

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [45]:
distance.to_csv("C:\\Users\\USER\\Desktop\\샘플데이터\\정제 데이터\\전처리데이터2.csv",
                header = True, index=False, sep=',', encoding='cp949')